sudo: required
language: cpp

stages:
  - compile
  - test
  
os:
  - osx
  - linux

compiler:
  - gcc
  - clang

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j8

test:
  script: ./build/tests/roar_test

notifications:
  email: false
