sudo: required
language: cpp

stages:
  - compile
  - test
  
env:
- BUILD_TYPE=Debug
- BUILD_TYPE=Release

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-10
    env:
      - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

  - os: linux
    dist: bionic
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-bionic-10
        packages:
          - clang-10
          - libc++-10-dev
          - libc++abi-10-dev
          - gcc-9
          - g++-9
    env:
      - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

  - os: osx
    osx_image: xcode12.2
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

  - os: osx
    osx_image: xcode12.2
    compiler: clang
    env:
      - MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"

script: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE && VERBOSE=1 cmake --build build --config $BUILD_TYPE -- -j8 && ./build/tests/roar_test

notifications:
  email: false
