sudo: required
language: cpp

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

stages:
  - compile
  - test
  
matrix:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
    env:
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"       
  - os: osx
    osx_image: xcode8
    env:
      - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
  - os: osx
    osx_image: xcode10.1
    env:
      - MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j8

test:
  script: ./build/tests/roar_test

notifications:
  email: false
