sudo: required
language: cpp

stages:
  - compile
  - test
  
matrix:
  include:
  - os: linux
    compiler: gcc
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  - os: linux
    compiler: clang
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-8.0
        packages:
          - clang-8.0
    env:
      - MATRIX_EVAL="CC=clang-8.0 && CXX=clang++-8.0"

  - os: osx
    osx_image: xcode10.1
    compiler: gcc
    env:
      - MATRIX_EVAL="brew install gcc && CC=gcc-8 && CXX=g++-8"

  - os: osx
    osx_image: xcode10.1
    compiler: clang
    env:
      - MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j8 && ./build/tests/roar_test

notifications:
  email: false
