sudo: required
language: cpp
dist: bionic
osx_image: xcode12.2

stages:
  - compile
  - test
  
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-10
    env:
      - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-bionic-10
        packages:
          - clang-10
          - libc++-10-dev
          - libc++abi-10-dev
          - gcc-10
          - g++-10
    env:
      - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

  - os: osx
    compiler: gcc
    env:
      - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

  - os: osx
    compiler: clang
    env:
      - MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"

script: mkdir build && cd build && VERBOSE=1 cmake -DCMAKE_BUILD_TYPE=Debug .. && VERBOSE=1 make -j8 && ./tests/roar_test

notifications:
  email: false
