name: Build Roar

on: [push]

jobs:
  build:
    name: "Build ${{ matrix.build_type }} of ${{ matrix.renderer }} backend on ${{ matrix.platform }}"
    strategy:
      fail-fast: false
      matrix:
        platform: [macos, ubuntu]
        build_type: [Debug, Release, RelWithDebInfo]
        renderer: [Metal, Vulkan]
    env:
      NUMCPUS: -j4
    runs-on: "${{ matrix.platform }}-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: CMake configure ${{ matrix.build_type }} on ${{ matrix.platform }}
        run: cmake -H"." -B"build/${{ matrix.platform }}/${{ matrix.build_type }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -DROAR_RENDER_TYPE="${{ matrix.renderer }}" -DROAR_BUILD_TESTS=1 -DROAR_BUILD_EDITOR=1
      - name: "CMake build ${{ matrix.build_type }} on ${{ matrix.platform }}"
        run: VERBOSE=1 cmake --build "build/${{ matrix.platform }}/${{ matrix.build_type }}" --config ${{ matrix.build_type }} -- ${{ env.NUMCPUS }}